version: '3.0'
services:
  test-chat-database:
    image: 'postgres:latest'
    container_name: test_chat_pg_db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - ${DATABASE_PORT}:5432
volumes:
  postgres:
